# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://creatorlxd.github.io/
date_format: "ordinal"
title: Creatorlxd's Blog
subtitle: "Creatorlxd's Blog"
description: "Creatorlxd的个人博客"
keywords: GameEngine,Creatorlxd
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Creatorlxd
organization: null
organization_url: null
github_username: creatorlxd
location: Hefei, China
email: creatorlxd@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: creatorlxd/creatorlxd.github.com

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: creatorlxd
#https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 'creatorlxd'
    repo: 'for-blog-comment'
    oauth:
        client_id: 'f851f17b004e293be801'
        client_secret: 'f93a2e5b3df7e3cb5fb631fff5cebdd7f95ec2b2'
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 'creatorlxd'
    repo: 'for-blog-comment'
    clientID: 'f851f17b004e293be801'
    clientSecret: 'f93a2e5b3df7e3cb5fb631fff5cebdd7f95ec2b2'
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-107692301-1
